declare module "@/integrations/supabase/client" {
  // This module is auto-generated by Lovable's Supabase integration at runtime.
  // We declare it here to satisfy TypeScript during development.
  export const supabase: any;
}
